### ISSUE TITLE
Error on post request

### ISSUE THREAD

**Issue by cash2900** [ranftldieterHub/Shape-Security-protection-reverse-engineering#4]
Getting this error every time i send the post request

TypeError: Cannot read property 'match' of undefined
    at getShapeData (C:\Users\user1\Downloads\Shape-Security-protection-reverse-engineering-master\worker.js:19:21)
    at Object.<anonymous> (C:\Users\user1\Downloads\Shape-Security-protection-reverse-engineering-master\worker.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:174:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
105 error

This is the response source:

{"result":{"status":"error"}}

**Comment by iamsr** [comment]
toEval data is changed now script needs updates.

**Comment by Petr2282** [comment]
> toEval data is changed now script needs updates.

do you know how to do it?
